# Generated by Django 4.2.2 on 2023-07-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0002_empresa_inmueble_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='inmuebleslist_app.empresa'),
            preserve_default=False,
        ),
    ]
