# Generated by Django 4.2.2 on 2023-07-06 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebleslist_app', '0004_alter_inmueble_empresa_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebleList', to='inmuebleslist_app.empresa'),
        ),
    ]
