# Generated by Django 4.2.2 on 2023-07-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_alter_inmueble_options_comentario_comentario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='numero_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
