# Generated by Django 4.2.2 on 2023-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_numbre',
            field=models.IntegerField(),
        ),
    ]
