# Generated by Django 4.2.2 on 2023-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_account_phone_numbre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_numbre',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
