# Generated by Django 4.2.2 on 2023-07-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_account_phone_numbre_account_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
